# Generated by Django 5.0.1 on 2024-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
    ]
